
services:
  api:
    build: .
    container_name: task-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: uvicorn app.infrastructure.http.fastapi_app:app --host 0.0.0.0 --port 8000 --reload